# Form implementation generated from reading ui file 'c:\Users\Kompik\Desktop\nd_12_Artem_Mykhailuk\qtdesigner\ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 31))
        self.label.setObjectName("label")
        self.result = QtWidgets.QLabel(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 60, 131, 31))
        self.result.setObjectName("result")
        self.usenumbers = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.usenumbers.setGeometry(QtCore.QRect(20, 120, 141, 20))
        self.usenumbers.setObjectName("usenumbers")
        self.useleters = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.useleters.setGeometry(QtCore.QRect(10, 160, 181, 20))
        self.useleters.setObjectName("useleters")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 93, 28))
        self.pushButton.setStyleSheet("color: red\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.usenumbers.setText(_translate("MainWindow", "Використати числа"))
        self.useleters.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.pushButton.setText(_translate("MainWindow", "Згеренувати"))
